#+LATEX_CLASS: article
#+AUTHOR: Andrew Ballinger
#+TITLE: Thinkful capstone proposal
#+DATE: Tue Aug 23 14:04:04 PDT 2016

* Goboard.link

Created for the angular capstone. A small spa for playing go online.

** Overview
A service similar to appear.in, except that you get a go board. There is an indicator for who's move it is.
Any number of clients can connect, and the game state will be automatically replicated across all devices.

Not prefering specific client/player relationships is convenient for changing devices, playing with both players on a single device, or playing with another player remotely.
Cheating by making moves for the other player is a non-problem in friendly play, since you could do the same thing on a physical board.

Visiting the site without an path will automatically generate a two-word path (such as goboard.link/monkey-lips).
Visiting the site at any other path will load the game state for that path, or create a new game at that path if one does not exist.

Firebase will handle both persistence and syncing across boards.

** Constraints
Since this is just for a course and I'm going to complete the first few versions at the office, I'm going to be time boxed rather then feature boxed for completion.
I'm going to limit my first version to the overview, and maybe integrate one or two of the nice-to-haves time permitting.

I don't plan on spending more then a day or two on this project... Though I might revisit it later.
If I were building this service on my choice-of-stack I would definitely choose Elm over Angular, maybe I'll port it in the undisclosed future.
#+LATEX: \clearpage

** Design aesthetic
   Lets go with....  Material design.
   Fitting, since a game board is a forced skeumorphism.
   
   Make all the pieces out of paper-style. Flat elements floating above one another.
   Maybe little cylinders sitting on a wire grid
   
** MVP Sketch
*** Screen is wider then it is tall
#+BEGIN_EXAMPLE
###################################################
## https://goboard.link/porkchop-sandwiches #######
###################################################
|   _______________________                       |
|  |                       |     Black to move    |
|  |                       |                      |
|  |      This is a        |     Last move was    |
|  |      go board.        |     23 seconds ago   |
|  |                       |                      |
|  |                       |                      |
|  |                       |                      |
|  |                       |                      |
|  |                       |                      |
|  |                       |                      |
|  |                       |                      |
|  |_______________________|  Some footer info    |
|_________________________________________________|
#+END_EXAMPLE
#+LATEX: \clearpage
*** Screen is taller then it is wide
#+BEGIN_EXAMPLE
###############################
## https://goboard.link/por...#
###############################
|   _______________________   |
|  |                       |  |
|  |                       |  |
|  |      This is a        |  |
|  |      go board.        |  |
|  |                       |  |
|  |                       |  |
|  |                       |  |
|  |                       |  |
|  |                       |  |
|  |                       |  |
|  |                       |  |
|  |_______________________|  |
|                             |
|       Black to move         |
|                             |
|      Last move was 23       |
|        seconds ago          |
|                             |
|                             |
|                             |
| Some footer info            |
|_____________________________|
#+END_EXAMPLE
#+LATEX: \clearpage

** Nice to haves
   It would be nice to have... (In no particular order)

*** Select board size
    The ability to choose to play with a 9X9 or other sized grid instead of 17x17

*** Scoring
    Automatically score

*** History and undo/redo
    The ability to view a game's history, branching undo tree (so you can go back, replay a game from a turning point, then compare the results)

*** Replay
    The ability to watch a game played in real/2x/10x time.

*** Player names
    The ability to type in your name as an additional reminder of which player is which color.

*** Login / Player history
    The ability to log in and see past/current games.
    Would be nice to have a menu that showed the status of each game, who's turn it is, and time since last play.

*** Tracking open games
    A lobby or spectator system

*** Rankings
    Some nice elo

*** Play vs CPU
    Play vs a bot... There are a few implementations/services.

*** Chat
    Some limited in-band chat functionality.

*** Back-end integrations
    Integrations with existing services (which for the most part have an old-school client and server model).

